### ISSUE TITLE
Some apps don’t hide labels

### ISSUE THREAD

**Issue by poppin-fresh** [cbyrne/ShyLabels#3]
Mine I particular are 
DiDi
Twitch 
Dropbox
Yubo
SongPop

**Comment by cbyrne** [comment]
Can you provide screenshots?

**Comment by poppin-fresh** [comment]
Attached
[cid:A16A7C1D-233B-402D-91D6-A282DC26E285-L0-001][cid:BA8318AF-0014-4EC6-8F6E-878B11A9E6DB-L0-001]

On 12 Jun 2020, at 23:43, Conor <notifications@github.com> wrote:

﻿

Can you provide screenshots?

**Comment by poppin-fresh** [comment]
![Uploading 84517259...]()

**Comment by cbyrne** [comment]
ShyLabels will be getting a rewrite in iOS 14, this issue will become irrelevant
