### ISSUE TITLE
Delay=0 doesn't affect other accessories on the label

### ISSUE THREAD

**Issue by cbyrne** [cbyrne/ShyLabels#4]
Apparently I’m to dump to post that in issues so here it is, also in issues

I‘m searching for a tweak that can hide the iCloudload icon under an offloaded apps. ShyLabels13 is the first tweak which even touched them, but only the Labels are hidden, the icons are still shy. [Here](https://imgur.com/a/uKN4JyW) is a vid of the bug.

(Taken from https://github.com/NoisyFlake/ShyLabels/issues/3)

**Comment by erik-404err** [comment]
I don’t know. I uninstalled anything that could cause a problem with the icons, so everything with the ability to modify my home screen. But still the same problem. Maybe it’s device dependent, but I don’t have another SE gen.1 on iOS 13.5 to test this ...

**Comment by cbyrne** [comment]
ShyLabels will be getting a rewrite in iOS 14, this issue will become irrelevant
